[package]
authors = ["Andy Philpotts <andy@failfree.net>"]
edition = "2018"
name = "dirt"
version = "0.1.0"
[dependencies]
anyhow = "1.0"
argh = "0.1"
blake2 = "0.9"
env_logger = "*"
log = "*"
hex = "0.4"
